resources:
  - name: conan_robotapp_github2
    type: GitRepo
    configuration:
      path: danimtb/robotapp
      gitProvider: danimtb_github

pipelines:
  - name: robotapp2
    steps:
      - name: build_robotapp_gcc8
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: czoido/pipelines-conanio-gcc8-armv7hf
                tag: latest
          inputResources:
            - name: conan_robotapp_github2
          integrations:
            - name: czoido_docker
            - name: environment
        execution:
          onExecute:
            - export CONAN_LOGIN_USERNAME=$int_environment_CONAN_LOGIN_USERNAME
            - export CONAN_PASSWORD=$int_environment_CONAN_PASSWORD
            - pip install conan --upgrade
            - pip install conan_package_tools
            - conan user
            - ls $res_conan_robotapp_github2_resourcePath
            - cd robotapp
            - conan profile new default --detect
            - conan profile show default
            - conan profile update settings.compiler.libcxx=libstdc++11 default
            - conan profile update settings.compiler.version=8 default
            - export CONAN_GCC_VERSIONS=8
            - python build.py