resources:
  - name: robotapp_github
    type: GitRepo
    configuration:
      path: czoido/robotapp
      gitProvider: czoido_github

pipelines:
  - name: robotapp_pipeline
    steps:
      - name: first_step_demo
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: conan_test_image
          dockerImageTag: $run_number
          inputResources:
            - name: robotapp_github
          integrations:
            - name: czoido_docker

      - name: second_step_demo
        type: Bash
        configuration:
          inputSteps:
            - name: first_step_demo
        execution:
          onExecute:
            - printenv
            - echo $res_robotapp_github_commitSha          

