resources:
  - name: conan_robotapp_github2
    type: GitRepo
    configuration:
      path: danimtb/robotapp
      gitProvider: danimtb_github

pipelines:
  - name: robotapp2
    steps:
      - name: configure_environment
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: danimtb/pipelines-conanio-gcc8-armv8
                tag: latest
          inputResources:
            - name: conan_robotapp_github2
          integrations:
            - name: artifactory
        execution:
          onExecute:
            - pip install conan --upgrade
            - conan user
            - conan remote remove conan-center
            - conan remote add artifactory https://art-yalla.jfrog-lab.com/artifactory/api/conan/conan-repo
            - conan user $int_artifactory_user --remote artifactory --password $int_artifactory_apikey
            - conan profile new default --detect
            - conan profile update settings.compiler.libcxx=libstdc++11 default
            - conan profile update settings.compiler.version=8 default
            - export CONAN_GCC_VERSIONS=8
            - conan profile show default
            - ls -lah ~/.conan
            - add_run_files ~/.conan conan_user_home
      - name: create_app
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: danimtb/pipelines-conanio-gcc8-armv8
                tag: latest
          inputResources:
            - name: conan_robotapp_github2
          inputSteps:
            - name: configure_environment
        execution:
          onExecute:
            - restore_run_files conan_user_home ~/.conan
            - conan profile show default
            - cd $res_conan_robotapp_github2_resourcePath
            - conan create . --profile default
            - add_run_files ~/.conan conan_user_home
      - name: upload_app
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: danimtb/pipelines-conanio-gcc8-armv8
                tag: latest
          inputSteps:
            - name: create_app
        execution:
          onExecute:
            - restore_run_files conan_user_home ~/.conan
            - conan upload --all --confirm *
