apiVersion: v1.1
resources:
  - name: robotapp_repo
    type: GitRepo
    configuration:
      gitProvider: GitHub_danimtb
      path: danimtb/robotapp
pipelines:
  - name: robotapp_ci
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: default_pool
    steps:
      - name: robotapp_ci1
        type: Bash
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
