resources:
  - name: conan_robotapp_github2
    type: GitRepo
    configuration:
      path: danimtb/robotapp
      gitProvider: danimtb_github

pipelines:
  - name: robotapp2
    steps:
      - name: configure_environment
        type: Bash
        configuration:
          affinityGroup: ci_group
          runtime:
            type: image
            image:
              custom:
                name: czoido/pipelines-conanio-gcc8-armv7hf
                tag: latest
          inputResources:
            - name: conan_robotapp_github2
          integrations:
            - name: czoido_docker
            - name: environment
        execution:
          onExecute:
            - pip install conan --upgrade
            - conan user
            - cd $res_conan_robotapp_github2_resourcePath
            - conan profile new default --detect
            - conan profile update settings.compiler.libcxx=libstdc++11 default
            - conan profile update settings.compiler.version=8 default
            - export CONAN_GCC_VERSIONS=8
            - conan profile show default
            - add_run_files ~/.conan conan_user_home
      - name: create_app
        type: Bash
        configuration:
          affinityGroup: ci_group
          runtime:
            type: image
            image:
              custom:
                name: czoido/pipelines-conanio-gcc8-armv7hf
                tag: latest
          inputResources:
            - name: conan_robotapp_github2
          inputSteps:
            - name: configure_environment
          integrations:
            - name: czoido_docker
            - name: environment
        execution:
          onExecute:
            - restore_run_files conan_user_home ~/.conan
            - cd $res_conan_robotapp_github2_resourcePath
            - conan profile show default
            - conan create . user/channel --profile default
            - add_run_files ~/.conan conan_user_home
      - name: upload_app
        type: Bash
        configuration:
          affinityGroup: ci_group
          runtime:
            type: image
            image:
              custom:
                name: czoido/pipelines-conanio-gcc8-armv7hf
                tag: latest
          inputSteps:
            - name: create_app
          integrations:
            - name: czoido_docker
            - name: environment
        execution:
          onExecute:
            - restore_run_files conan_user_home ~/.conan
            - export CONAN_LOGIN_USERNAME=$int_environment_CONAN_LOGIN_USERNAME
            - export CONAN_PASSWORD=$int_environment_CONAN_PASSWORD
            - conan upload robotapp/1.0@user/channel --all
