resources:
  - name: robotapp_github
    type: GitRepo
    configuration:
      gitProvider: czoido_github
      path: czoido/robotapp
      branches:
        include: master
      buildOn:
         commit: true
         pullRequestCreate: true
         releaseCreate: true
         tagCreate: true
pipelines:
  - name: barebones_pipeline
    configuration:
      runtime:       
        type: image
        image:
           custom:
             name: conanio/gcc6-armv7hf
             tag: latest
             registry: czoido_docker
    steps:
    - name: step_1
      type: Bash
      configuration:
        inputResources:
          - name: robotapp_github
            trigger: true
      execution:
        onExecute:
          - printenv
          - echo $res_robotapp_github_commitSha
 
    - name: step_2
      type: Bash
      configuration:
        inputSteps:
          - name: step_1
      execution:
        onExecute:
          - printenv
 
    - name: step_3
      type: Bash
      configuration:
        inputSteps:
          - name: step_1
      execution:
        onExecute:
          - printenv
 
    - name: step_4
      type: Bash
      configuration:
        inputSteps:
          - name: step_2
          - name: step_3
      execution:
        onExecute:
          - printenv