resources:
  - name: robotapp_repo
    type: GitRepo
    configuration:
      gitProvider: GitHub_danimtb
      path: danimtb/robotapp
      branches:
        include: master
pipelines:
  - name: robotapp_ci
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: conanio/gcc72
            tag: latest
    steps:
      - name: Trigger
        type: Bash
        configuration:
          inputResources:
            - name: robotapp_repo
              trigger: true
      - name: Step1
        type: Bash
        execution:
          onExecute:
            - echo "I'm running in container!!!"
