resources:
  - name: conan_robotapp_github2
    type: GitRepo
    configuration:
      path: danimtb/robotapp
      gitProvider: danimtb_github

pipelines:
  - name: robotapp2
    steps:
      - name: configure_environment
        type: Bash
        configuration:
          affinityGroup: ci_group
          runtime:
            type: image
            image:
              custom:
                name: danimtb/pipelines-conanio-gcc8-armv8
                tag: latest
          inputResources:
            - name: conan_robotapp_github2
          integrations:
            - name: environment
            - name: artifactory
        execution:
          onExecute:
            - pip install conan --upgrade
            - conan user
            - conan remote remove conan-center
            - conan remote add artifactory $int_artifactory_url
            - conan user $int_artifactory_user --remote artifactory --password $int_artifactory_apikey
            - conan profile new default --detect
            - conan profile update settings.compiler.libcxx=libstdc++11 default
            - conan profile update settings.compiler.version=8 default
            - export CONAN_GCC_VERSIONS=8
            - conan profile show default
            - conan remote add artifactory int_artifactory_url
            - add_run_files ~/.conan conan_user_home
      - name: create_app
        type: Bash
        configuration:
          affinityGroup: ci_group
          runtime:
            type: image
            image:
              custom:
                name: danimtb/pipelines-conanio-gcc8-armv8
                tag: latest
          inputResources:
            - name: conan_robotapp_github2
          inputSteps:
            - name: configure_environment
          integrations:
            - name: environment
            - name: artifactory
        execution:
          onExecute:
            - restore_run_files conan_user_home ~/.conan
            - cd $res_conan_robotapp_github2_resourcePath
            - conan profile show default
            - conan create . user/channel --profile default
            - add_run_files ~/.conan conan_user_home
      - name: upload_app
        type: Bash
        configuration:
          affinityGroup: ci_group
          runtime:
            type: image
            image:
              custom:
                name: danimtb/pipelines-conanio-gcc8-armv8
                tag: latest
          inputSteps:
            - name: create_app
        execution:
          onExecute:
            - restore_run_files conan_user_home ~/.conan
            - conan upload robotapp/1.0@user/channel --all
