apiVersion: v1.1
resources:
  - name: danimtb/robotapp
    type: GitRepo
    gitProvider: GitHub
    path: robotapp/
pipelines:
  - name: robotapp_ci
    steps:
      - name: robotapp_ci1
        type: Bash
        configuration:
          runtime:
          type: default_pool
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
